/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.10.1/samples
 */
plugins {
    java
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"  // Build using ./gradlew shadowJar to include dependencies in build
}

application {
    mainClass.set("main")
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

version = "1.0"

repositories {
    mavenCentral()
}

//https://github.com/googleapis/google-auth-library-java
dependencies {
    implementation("com.google.api-client:google-api-client:2.0.0")
    implementation("com.google.oauth-client:google-oauth-client-jetty:1.34.1")
    implementation("com.google.apis:google-api-services-drive:v3-rev20220815-2.0.0")
    implementation("com.google.oauth-client:google-oauth-client:1.34.1") 
    // Last one required for refresh token
}